services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      # Mount the src directory for hot-reloading
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true

volumes:
  redis-data:
